import AsyncStorage from '@react-native-async-storage/async-storage';
import { Animal, Farm, Transaction, HealthRecord } from '../types';
import { InventoryItem } from '@/store/inventoryStore';
import { Reminder } from '@/store/reminderStore';
import { BreedingRecord } from '@/types/breeding';

// Mock Farms Data
const mockFarms: Farm[] = [
  {
    id: 'farm-1',
    name: 'Green Valley Farm',
    location: 'California, USA',
    size: 150,
    sizeUnit: 'acres',
    type: 'Mixed',
    createdAt: new Date('2023-03-20').toISOString(),
    updatedAt: new Date('2024-01-10').toISOString(),
  },
  {
    id: 'farm-2',
    name: 'Sunset Ranch',
    location: 'Texas, USA',
    size: 200,
    sizeUnit: 'acres',
    type: 'Livestock',
    createdAt: new Date('2022-05-15').toISOString(),
    updatedAt: new Date('2024-01-12').toISOString(),
  },
];

// Mock Animals Data
const mockAnimals: Animal[] = [
  {
    id: 'animal-1',
    farmId: 'farm-1',
    identificationNumber: 'C001',
    species: 'Cattle',
    breed: 'Holstein',
    gender: 'Female',
    birthDate: '2022-05-15',
    acquisitionDate: '2022-06-01',
    status: 'Healthy',
    weight: 450,
    weightUnit: 'kg',
    price: 1200,
    acquisitionPrice: 1000,
    notes: 'High milk production cow',
    createdAt: new Date('2022-06-01').toISOString(),
    updatedAt: new Date('2024-01-15').toISOString(),
    age: 2,
    healthStatus: 'healthy',
    type: 'Cattle',
  },
  {
    id: 'animal-2',
    farmId: 'farm-1',
    identificationNumber: 'C002',
    species: 'Cattle',
    breed: 'Angus',
    gender: 'Male',
    birthDate: '2021-08-20',
    acquisitionDate: '2021-09-10',
    status: 'Healthy',
    weight: 600,
    weightUnit: 'kg',
    price: 1800,
    acquisitionPrice: 1500,
    notes: 'Prime breeding bull',
    createdAt: new Date('2021-09-10').toISOString(),
    updatedAt: new Date('2024-01-10').toISOString(),
    age: 3,
    healthStatus: 'healthy',
    type: 'Cattle',
  },
  {
    id: 'animal-3',
    farmId: 'farm-1',
    identificationNumber: 'G001',
    species: 'Goat',
    breed: 'Boer',
    gender: 'Female',
    birthDate: '2023-02-10',
    acquisitionDate: '2023-03-01',
    status: 'Healthy',
    weight: 45,
    weightUnit: 'kg',
    price: 300,
    acquisitionPrice: 250,
    notes: 'Good for meat production',
    createdAt: new Date('2023-03-01').toISOString(),
    updatedAt: new Date('2024-01-05').toISOString(),
    age: 1,
    healthStatus: 'healthy',
    type: 'Goat',
  },
  {
    id: 'animal-4',
    farmId: 'farm-2',
    identificationNumber: 'C001',
    species: 'Cattle',
    breed: 'Brahman',
    gender: 'Male',
    birthDate: '2020-11-05',
    acquisitionDate: '2021-01-15',
    status: 'Healthy',
    weight: 750,
    weightUnit: 'kg',
    price: 2500,
    acquisitionPrice: 2000,
    notes: 'Excellent breeding stock',
    createdAt: new Date('2021-01-15').toISOString(),
    updatedAt: new Date('2024-01-12').toISOString(),
    age: 4,
    healthStatus: 'healthy',
    type: 'Cattle',
  },
  {
    id: 'animal-5',
    farmId: 'farm-1',
    identificationNumber: 'S001',
    species: 'Sheep',
    breed: 'Merino',
    gender: 'Female',
    birthDate: '2023-04-12',
    acquisitionDate: '2023-05-01',
    status: 'Healthy',
    weight: 60,
    weightUnit: 'kg',
    price: 200,
    acquisitionPrice: 180,
    notes: 'High quality wool producer',
    createdAt: new Date('2023-05-01').toISOString(),
    updatedAt: new Date('2024-01-08').toISOString(),
    age: 1,
    healthStatus: 'healthy',
    type: 'Sheep',
  },
  {
    id: 'animal-6',
    farmId: 'farm-1',
    identificationNumber: 'C003',
    species: 'Cattle',
    breed: 'Jersey',
    gender: 'Female',
    birthDate: '2022-12-03',
    acquisitionDate: '2023-01-15',
    status: 'Healthy',
    weight: 380,
    weightUnit: 'kg',
    price: 1100,
    acquisitionPrice: 950,
    notes: 'Excellent milk quality',
    createdAt: new Date('2023-01-15').toISOString(),
    updatedAt: new Date('2024-01-20').toISOString(),
    age: 1,
    healthStatus: 'healthy',
    type: 'Cattle',
  },
  {
    id: 'animal-7',
    farmId: 'farm-2',
    identificationNumber: 'P001',
    species: 'Pig',
    breed: 'Yorkshire',
    gender: 'Male',
    birthDate: '2023-06-20',
    acquisitionDate: '2023-07-10',
    status: 'Healthy',
    weight: 120,
    weightUnit: 'kg',
    price: 400,
    acquisitionPrice: 350,
    notes: 'Fast growing breed',
    createdAt: new Date('2023-07-10').toISOString(),
    updatedAt: new Date('2024-01-18').toISOString(),
    age: 1,
    healthStatus: 'healthy',
    type: 'Pig',
  },
  {
    id: 'animal-8',
    farmId: 'farm-1',
    identificationNumber: 'CH001',
    species: 'Chicken',
    breed: 'Rhode Island Red',
    gender: 'Female',
    birthDate: '2023-09-15',
    acquisitionDate: '2023-10-01',
    status: 'Healthy',
    weight: 2.5,
    weightUnit: 'kg',
    price: 25,
    acquisitionPrice: 20,
    notes: 'Good egg layer',
    createdAt: new Date('2023-10-01').toISOString(),
    updatedAt: new Date('2024-01-22').toISOString(),
    age: 0,
    healthStatus: 'healthy',
    type: 'Chicken',
  },
  {
    id: 'animal-9',
    farmId: 'farm-2',
    identificationNumber: 'H001',
    species: 'Horse',
    breed: 'Quarter Horse',
    gender: 'Male',
    birthDate: '2019-04-08',
    acquisitionDate: '2020-05-15',
    status: 'Healthy',
    weight: 500,
    weightUnit: 'kg',
    price: 5000,
    acquisitionPrice: 4500,
    notes: 'Well trained riding horse',
    createdAt: new Date('2020-05-15').toISOString(),
    updatedAt: new Date('2024-01-25').toISOString(),
    age: 5,
    healthStatus: 'healthy',
    type: 'Horse',
  },
  {
    id: 'animal-10',
    farmId: 'farm-1',
    identificationNumber: 'D001',
    species: 'Duck',
    breed: 'Pekin',
    gender: 'Female',
    birthDate: '2023-08-12',
    acquisitionDate: '2023-09-01',
    status: 'Healthy',
    weight: 3.2,
    weightUnit: 'kg',
    price: 30,
    acquisitionPrice: 25,
    notes: 'Good for meat and eggs',
    createdAt: new Date('2023-09-01').toISOString(),
    updatedAt: new Date('2024-01-28').toISOString(),
    age: 0,
    healthStatus: 'healthy',
    type: 'Duck',
  },
  {
    id: 'animal-11',
    farmId: 'farm-2',
    identificationNumber: 'S002',
    species: 'Sheep',
    breed: 'Suffolk',
    gender: 'Male',
    birthDate: '2022-11-20',
    acquisitionDate: '2023-01-05',
    status: 'Healthy',
    weight: 85,
    weightUnit: 'kg',
    price: 350,
    acquisitionPrice: 300,
    notes: 'Good breeding ram',
    createdAt: new Date('2023-01-05').toISOString(),
    updatedAt: new Date('2024-01-30').toISOString(),
    age: 1,
    healthStatus: 'healthy',
    type: 'Sheep',
  },
  {
    id: 'animal-12',
    farmId: 'farm-1',
    identificationNumber: 'G002',
    species: 'Goat',
    breed: 'Nubian',
    gender: 'Female',
    birthDate: '2023-01-25',
    acquisitionDate: '2023-03-10',
    status: 'Healthy',
    weight: 55,
    weightUnit: 'kg',
    price: 280,
    acquisitionPrice: 240,
    notes: 'High milk production',
    createdAt: new Date('2023-03-10').toISOString(),
    updatedAt: new Date('2024-02-01').toISOString(),
    age: 1,
    healthStatus: 'healthy',
    type: 'Goat',
  },
  {
    id: 'animal-13',
    farmId: 'farm-2',
    identificationNumber: 'T001',
    species: 'Turkey',
    breed: 'Bronze',
    gender: 'Male',
    birthDate: '2023-05-18',
    acquisitionDate: '2023-06-15',
    status: 'Healthy',
    weight: 8.5,
    weightUnit: 'kg',
    price: 80,
    acquisitionPrice: 70,
    notes: 'Heritage breed turkey',
    createdAt: new Date('2023-06-15').toISOString(),
    updatedAt: new Date('2024-02-03').toISOString(),
    age: 1,
    healthStatus: 'healthy',
    type: 'Turkey',
  },
  {
    id: 'animal-14',
    farmId: 'farm-1',
    identificationNumber: 'R001',
    species: 'Rabbit',
    breed: 'New Zealand White',
    gender: 'Female',
    birthDate: '2023-10-05',
    acquisitionDate: '2023-11-01',
    status: 'Healthy',
    weight: 4.2,
    weightUnit: 'kg',
    price: 45,
    acquisitionPrice: 40,
    notes: 'Good for meat production',
    createdAt: new Date('2023-11-01').toISOString(),
    updatedAt: new Date('2024-02-05').toISOString(),
    age: 0,
    healthStatus: 'healthy',
    type: 'Rabbit',
  },
  {
    id: 'animal-15',
    farmId: 'farm-2',
    identificationNumber: 'C002',
    species: 'Cattle',
    breed: 'Hereford',
    gender: 'Female',
    birthDate: '2021-07-14',
    acquisitionDate: '2021-09-20',
    status: 'Healthy',
    weight: 520,
    weightUnit: 'kg',
    price: 1600,
    acquisitionPrice: 1400,
    notes: 'Excellent mother cow',
    createdAt: new Date('2021-09-20').toISOString(),
    updatedAt: new Date('2024-02-07').toISOString(),
    age: 3,
    healthStatus: 'healthy',
    type: 'Cattle',
  },
  {
    id: 'animal-16',
    farmId: 'farm-1',
    identificationNumber: 'C004',
    species: 'Cattle',
    breed: 'Simmental',
    gender: 'Female',
    birthDate: '2022-03-11',
    acquisitionDate: '2022-04-01',
    status: 'Healthy',
    weight: 430,
    weightUnit: 'kg',
    price: 1300,
    acquisitionPrice: 1100,
    notes: 'Good milk yield and temperament',
    createdAt: new Date('2022-04-01').toISOString(),
    updatedAt: new Date('2024-02-10').toISOString(),
    age: 2,
    healthStatus: 'healthy',
    type: 'Cattle',
  },
  {
    id: 'animal-17',
    farmId: 'farm-2',
    identificationNumber: 'P002',
    species: 'Pig',
    breed: 'Duroc',
    gender: 'Female',
    birthDate: '2023-01-19',
    acquisitionDate: '2023-02-05',
    status: 'Healthy',
    weight: 95,
    weightUnit: 'kg',
    price: 380,
    acquisitionPrice: 320,
    notes: 'Strong growth performance',
    createdAt: new Date('2023-02-05').toISOString(),
    updatedAt: new Date('2024-02-08').toISOString(),
    age: 1,
    healthStatus: 'healthy',
    type: 'Pig',
  },
  {
    id: 'animal-18',
    farmId: 'farm-1',
    identificationNumber: 'CH002',
    species: 'Chicken',
    breed: 'Leghorn',
    gender: 'Female',
    birthDate: '2023-10-10',
    acquisitionDate: '2023-10-25',
    status: 'Healthy',
    weight: 2.1,
    weightUnit: 'kg',
    price: 22,
    acquisitionPrice: 18,
    notes: 'High egg production layer',
    createdAt: new Date('2023-10-25').toISOString(),
    updatedAt: new Date('2024-02-09').toISOString(),
    age: 0,
    healthStatus: 'healthy',
    type: 'Chicken',
  },
  {
    id: 'animal-19',
    farmId: 'farm-2',
    identificationNumber: 'H002',
    species: 'Horse',
    breed: 'Arabian',
    gender: 'Female',
    birthDate: '2018-06-02',
    acquisitionDate: '2019-01-10',
    status: 'Healthy',
    weight: 470,
    weightUnit: 'kg',
    price: 6500,
    acquisitionPrice: 6000,
    notes: 'Endurance horse, calm under saddle',
    createdAt: new Date('2019-01-10').toISOString(),
    updatedAt: new Date('2024-02-11').toISOString(),
    age: 6,
    healthStatus: 'healthy',
    type: 'Horse',
  },
  {
    id: 'animal-20',
    farmId: 'farm-1',
    identificationNumber: 'S003',
    species: 'Sheep',
    breed: 'Dorper',
    gender: 'Female',
    birthDate: '2023-02-22',
    acquisitionDate: '2023-03-15',
    status: 'Healthy',
    weight: 62,
    weightUnit: 'kg',
    price: 210,
    acquisitionPrice: 185,
    notes: 'Good meat conformation',
    createdAt: new Date('2023-03-15').toISOString(),
    updatedAt: new Date('2024-02-12').toISOString(),
    age: 1,
    healthStatus: 'healthy',
    type: 'Sheep',
  },
];

// Mock Transactions Data
const mockTransactions: Transaction[] = [
  {
    id: 'trans-1',
    farmId: 'farm-1',
    type: 'Income',
    category: 'Sales',
    amount: 2500,
    description: 'Milk sales - weekly',
    date: '2024-01-15',
    paymentMethod: 'Bank Transfer',
    reference: 'REF-001',
    createdAt: new Date('2024-01-15').toISOString(),
    updatedAt: new Date('2024-01-15').toISOString(),
  },
  {
    id: 'trans-2',
    farmId: 'farm-1',
    type: 'Expense',
    category: 'Feed',
    amount: 800,
    description: 'Cattle feed purchase',
    date: '2024-01-10',
    paymentMethod: 'Cash',
    reference: 'REF-002',
    createdAt: new Date('2024-01-10').toISOString(),
    updatedAt: new Date('2024-01-10').toISOString(),
  },
  {
    id: 'trans-3',
    farmId: 'farm-1',
    type: 'Expense',
    category: 'Medication',
    amount: 150,
    description: 'Vaccination supplies',
    date: '2024-01-08',
    paymentMethod: 'Credit Card',
    reference: 'REF-003',
    createdAt: new Date('2024-01-08').toISOString(),
    updatedAt: new Date('2024-01-08').toISOString(),
  },
  {
    id: 'trans-4',
    farmId: 'farm-2',
    type: 'Income',
    category: 'Sales',
    amount: 5000,
    description: 'Cattle sale - 2 head',
    date: '2024-01-12',
    paymentMethod: 'Bank Transfer',
    reference: 'REF-004',
    createdAt: new Date('2024-01-12').toISOString(),
    updatedAt: new Date('2024-01-12').toISOString(),
  },
  {
    id: 'trans-5',
    farmId: 'farm-1',
    type: 'Income',
    category: 'Sales',
    amount: 1200,
    description: 'Wool sales',
    date: '2024-01-05',
    paymentMethod: 'Cash',
    reference: 'REF-005',
    createdAt: new Date('2024-01-05').toISOString(),
    updatedAt: new Date('2024-01-05').toISOString(),
  },
];

// Mock Health Records Data
const mockHealthRecords: HealthRecord[] = [
  {
    id: 'health-1',
    description: 'Annual vaccination checkup',
    diagnosis: 'Healthy, due for routine vaccination',
    dosage: '2ml subcutaneous injection',
    farmId: 'farm-1',
    animalId: 'animal-1',
    type: 'Vaccination',
    date: '2024-01-10',
    treatment: 'Annual vaccination',
    medication: 'Bovine vaccine',
    cost: 25,
    veterinarian: 'Dr. Smith',
    notes: 'Routine annual vaccination',
    createdAt: new Date('2024-01-10').toISOString(),
    updatedAt: new Date('2024-01-10').toISOString(),
  },
  {
    id: 'health-2',
    description: 'Routine hoof maintenance',
    diagnosis: 'Overgrown hooves requiring trimming',
    dosage: 'Topical application',
    farmId: 'farm-1',
    animalId: 'animal-2',
    type: 'Treatment',
    date: '2024-01-08',
    treatment: 'Hoof trimming',
    medication: 'Antiseptic spray',
    cost: 40,
    veterinarian: 'Dr. Johnson',
    notes: 'Preventive hoof care',
    createdAt: new Date('2024-01-08').toISOString(),
    updatedAt: new Date('2024-01-08').toISOString(),
  },
  {
    id: 'health-3',
    description: 'Routine health examination',
    diagnosis: 'Animal in excellent health',
    dosage: 'N/A',
    farmId: 'farm-2',
    animalId: 'animal-4',
    type: 'Checkup',
    date: '2024-01-12',
    treatment: 'General health check',
    medication: 'None',
    cost: 60,
    veterinarian: 'Dr. Williams',
    notes: 'Excellent health condition',
    createdAt: new Date('2024-01-12').toISOString(),
    updatedAt: new Date('2024-01-12').toISOString(),
  },
  {
    id: 'health-4',
    description: 'Post-partum check',
    diagnosis: 'Normal recovery after calving',
    dosage: 'Observation only',
    farmId: 'farm-1',
    animalId: 'animal-16',
    type: 'Checkup',
    date: '2024-02-14',
    treatment: 'Physical examination and observation',
    medication: 'None',
    cost: 35,
    veterinarian: 'Dr. Smith',
    notes: 'No complications detected',
    createdAt: new Date('2024-02-14').toISOString(),
    updatedAt: new Date('2024-02-14').toISOString(),
  },
  {
    id: 'health-5',
    description: 'Respiratory infection treatment',
    diagnosis: 'Mild upper respiratory infection',
    dosage: '10ml antibiotic once daily for 5 days',
    farmId: 'farm-2',
    animalId: 'animal-17',
    type: 'Treatment',
    date: '2024-02-09',
    treatment: 'Antibiotic and anti-inflammatory',
    medication: 'Long-acting oxytetracycline',
    cost: 55,
    veterinarian: 'Dr. Johnson',
    notes: 'Responding well to treatment, follow-up in 7 days',
    createdAt: new Date('2024-02-09').toISOString(),
    updatedAt: new Date('2024-02-10').toISOString(),
  },
  {
    id: 'health-6',
    description: 'De-worming and Parasite control',
    diagnosis: 'Routine De-worming program',
    dosage: 'Weight-based oral drench',
    farmId: 'farm-1',
    animalId: 'animal-20',
    type: 'Other',
    date: '2024-02-05',
    treatment: 'Broad-spectrum dewormer',
    medication: 'Ivermectin oral drench',
    cost: 30,
    veterinarian: 'Dr. Williams',
    notes: 'Scheduled as part of quarterly parasite control plan',
    createdAt: new Date('2024-02-05').toISOString(),
    updatedAt: new Date('2024-02-05').toISOString(),
  },
];

// Mock Inventory Items
const mockInventory: InventoryItem[] = [
  {
    id: 'inv-1',
    farmId: 'farm-1',
    name: 'Cattle Feed (25kg)',
    category: 'Feed',
    quantity: 42,
    unit: 'bags',
    minimumStock: 10,
    cost: 8500,
    supplier: 'AgroFeed Supplies Ltd',
    createdAt: new Date('2024-01-05').toISOString(),
    updatedAt: new Date('2024-01-20').toISOString(),
  },
  {
    id: 'inv-2',
    farmId: 'farm-1',
    name: 'Poultry Layer Mash',
    category: 'Feed',
    quantity: 18,
    unit: 'bags',
    minimumStock: 5,
    cost: 6200,
    supplier: 'GreenFeed Co.',
    createdAt: new Date('2024-01-08').toISOString(),
    updatedAt: new Date('2024-01-18').toISOString(),
  },
  {
    id: 'inv-3',
    farmId: 'farm-1',
    name: 'Ivermectin Injection',
    category: 'Medicine',
    quantity: 24,
    unit: 'vials',
    minimumStock: 5,
    expiryDate: '2025-06-15',
    cost: 3200,
    supplier: 'VetPharm Nigeria',
    createdAt: new Date('2024-01-10').toISOString(),
    updatedAt: new Date('2024-01-22').toISOString(),
  },
  {
    id: 'inv-4',
    farmId: 'farm-1',
    name: 'Oxytetracycline LA',
    category: 'Medicine',
    quantity: 8,
    unit: 'bottles',
    minimumStock: 3,
    expiryDate: '2025-03-01',
    cost: 4500,
    supplier: 'VetPharm Nigeria',
    createdAt: new Date('2024-01-12').toISOString(),
    updatedAt: new Date('2024-02-01').toISOString(),
  },
  {
    id: 'inv-5',
    farmId: 'farm-1',
    name: 'Mineral Salt Lick Block',
    category: 'Supplement',
    quantity: 15,
    unit: 'blocks',
    minimumStock: 8,
    cost: 1800,
    supplier: 'FarmCare Essentials',
    createdAt: new Date('2024-01-06').toISOString(),
    updatedAt: new Date('2024-01-28').toISOString(),
  },
  {
    id: 'inv-6',
    farmId: 'farm-1',
    name: 'Milking Machine Rubber Liners',
    category: 'Equipment',
    quantity: 6,
    unit: 'pairs',
    minimumStock: 2,
    cost: 7500,
    supplier: 'DairyTech Solutions',
    createdAt: new Date('2024-01-15').toISOString(),
    updatedAt: new Date('2024-02-05').toISOString(),
  },
  {
    id: 'inv-7',
    farmId: 'farm-1',
    name: 'Disinfectant Concentrate',
    category: 'Medicine',
    quantity: 3,
    unit: 'litres',
    minimumStock: 5,
    expiryDate: '2025-09-20',
    cost: 2100,
    supplier: 'VetPharm Nigeria',
    createdAt: new Date('2024-01-20').toISOString(),
    updatedAt: new Date('2024-02-03').toISOString(),
  },
  {
    id: 'inv-8',
    farmId: 'farm-1',
    name: 'Wheat Bran (50kg)',
    category: 'Feed',
    quantity: 28,
    unit: 'bags',
    minimumStock: 10,
    cost: 4200,
    supplier: 'AgroFeed Supplies Ltd',
    createdAt: new Date('2024-01-18').toISOString(),
    updatedAt: new Date('2024-02-02').toISOString(),
  },
  {
    id: 'inv-9',
    farmId: 'farm-2',
    name: 'Horse Feed Premium Mix',
    category: 'Feed',
    quantity: 12,
    unit: 'bags',
    minimumStock: 5,
    cost: 9500,
    supplier: 'Equine Nutrition Co.',
    createdAt: new Date('2024-01-22').toISOString(),
    updatedAt: new Date('2024-02-01').toISOString(),
  },
  {
    id: 'inv-10',
    farmId: 'farm-2',
    name: 'Veterinary First Aid Kit',
    category: 'Equipment',
    quantity: 2,
    unit: 'kits',
    minimumStock: 1,
    cost: 12500,
    supplier: 'VetPharm Nigeria',
    createdAt: new Date('2024-01-25').toISOString(),
    updatedAt: new Date('2024-02-08').toISOString(),
  },
];

// Mock Reminders
const mockReminders: Reminder[] = [
  {
    id: 'rem-1',
    farmId: 'farm-1',
    animalId: 'animal-1',
    title: 'Annual vaccination for Holstein C001',
    type: 'vaccination',
    dueDate: '2025-01-15',
    status: 'active',
    notes: 'Annual booster - Foot and Mouth Disease',
    recurring: true,
    recurringDays: 365,
    createdAt: new Date('2024-01-15').toISOString(),
    updatedAt: new Date('2024-01-15').toISOString(),
  },
  {
    id: 'rem-2',
    farmId: 'farm-1',
    animalId: 'animal-3',
    title: 'Quarterly deworming - Goat G001',
    type: 'health_checkup',
    dueDate: '2025-02-20',
    status: 'active',
    notes: 'Rotate dewormer type this quarter',
    recurring: true,
    recurringDays: 90,
    createdAt: new Date('2024-02-20').toISOString(),
    updatedAt: new Date('2024-02-20').toISOString(),
  },
  {
    id: 'rem-3',
    farmId: 'farm-1',
    title: 'Restock poultry layer mash',
    type: 'inventory_restock',
    dueDate: '2025-03-01',
    status: 'active',
    notes: 'Order from GreenFeed Co. - 10 bags minimum',
    createdAt: new Date('2024-02-25').toISOString(),
    updatedAt: new Date('2024-02-25').toISOString(),
  },
  {
    id: 'rem-4',
    farmId: 'farm-1',
    animalId: 'animal-2',
    title: 'Breeding health check - Angus Bull C002',
    type: 'breeding',
    dueDate: '2025-02-10',
    status: 'active',
    notes: 'Pre-breeding semen quality check',
    createdAt: new Date('2024-02-01').toISOString(),
    updatedAt: new Date('2024-02-01').toISOString(),
  },
  {
    id: 'rem-5',
    farmId: 'farm-1',
    animalId: 'animal-16',
    title: 'Post-calving checkup - Simmental C004',
    type: 'health_checkup',
    dueDate: '2025-01-25',
    status: 'completed',
    notes: 'All clear - cow and calf healthy',
    recurring: false,
    createdAt: new Date('2024-01-20').toISOString(),
    updatedAt: new Date('2024-02-05').toISOString(),
    completedAt: new Date('2024-01-28').toISOString(),
  },
  {
    id: 'rem-6',
    farmId: 'farm-2',
    animalId: 'animal-19',
    title: 'Equine dental check - Arabian H002',
    type: 'health_checkup',
    dueDate: '2025-03-15',
    status: 'active',
    notes: 'Annual floating and oral exam',
    recurring: true,
    recurringDays: 365,
    createdAt: new Date('2024-03-01').toISOString(),
    updatedAt: new Date('2024-03-01').toISOString(),
  },
];

// Mock Breeding Records
const mockBreeding: BreedingRecord[] = [
  {
    id: 'breed-1',
    farmId: 'farm-1',
    femaleAnimalId: 'animal-1',
    maleAnimalId: 'animal-2',
    breedingDate: '2024-11-20',
    expectedBirthDate: '2025-08-27',
    method: 'Natural',
    status: 'Pregnant',
    notes: 'Holstein x Angus cross. Confirmed pregnant via vet check.',
    createdAt: new Date('2024-11-20').toISOString(),
    updatedAt: new Date('2024-12-15').toISOString(),
  },
  {
    id: 'breed-2',
    farmId: 'farm-1',
    femaleAnimalId: 'animal-16',
    breedingDate: '2024-04-15',
    expectedBirthDate: '2025-01-15',
    actualBirthDate: '2025-01-18',
    method: 'Artificial Insemination',
    status: 'Successful',
    litterSize: 1,
    notes: 'Simmental x AI (sexed semen). Healthy bull calf delivered.',
    createdAt: new Date('2024-04-15').toISOString(),
    updatedAt: new Date('2025-01-20').toISOString(),
  },
  {
    id: 'breed-3',
    farmId: 'farm-1',
    femaleAnimalId: 'animal-12',
    maleAnimalId: 'animal-3',
    breedingDate: '2025-01-10',
    expectedBirthDate: '2025-06-10',
    method: 'Natural',
    status: 'Confirmed',
    notes: 'Nubian x Boer cross. Pregnancy test in 30 days.',
    createdAt: new Date('2025-01-10').toISOString(),
    updatedAt: new Date('2025-01-10').toISOString(),
  },
  {
    id: 'breed-4',
    farmId: 'farm-1',
    femaleAnimalId: 'animal-5',
    breedingDate: '2024-12-01',
    expectedBirthDate: '2025-05-08',
    method: 'Natural',
    status: 'Pregnant',
    notes: 'Merino ewe confirmed pregnant. Expecting twins.',
    createdAt: new Date('2024-12-01').toISOString(),
    updatedAt: new Date('2025-01-05').toISOString(),
  },
  {
    id: 'breed-5',
    farmId: 'farm-2',
    femaleAnimalId: 'animal-19',
    maleAnimalId: 'animal-9',
    breedingDate: '2024-10-05',
    expectedBirthDate: '2025-09-07',
    method: 'Natural',
    status: 'Pregnant',
    notes: 'Arabian x Quarter Horse cross. Foal expected September.',
    createdAt: new Date('2024-10-05').toISOString(),
    updatedAt: new Date('2024-11-20').toISOString(),
  },
];

// Mock User Data — only populated when EXPO_PUBLIC_DEMO_MODE env var is explicitly set
const mockUsers = process.env.EXPO_PUBLIC_DEMO_MODE === '1' ? [
  {
    id: 'user-1',
    email: 'demo@veelink.com',
    password: 'demo123',
    name: 'Demo User',
    createdAt: new Date('2023-01-01').toISOString(),
    updatedAt: new Date('2024-01-15').toISOString(),
  },
] : [];

/**
 * Returns a Set of IDs for the given demo data type.
 * Used by "Clear Demo Data" to remove only demo-seeded records while
 * keeping any user-created data intact.
 */
export const getDemoIds = (type: 'farms' | 'animals' | 'transactions' | 'healthRecords' | 'inventory' | 'reminders' | 'breeding'): Set<string> => {
  switch (type) {
    case 'farms':
      return new Set(mockFarms.map(f => f.id));
    case 'animals':
      return new Set(mockAnimals.map(a => a.id));
    case 'transactions':
      return new Set(mockTransactions.map(t => t.id));
    case 'healthRecords':
      return new Set(mockHealthRecords.map(r => r.id));
    case 'inventory':
      return new Set(mockInventory.map(i => i.id));
    case 'reminders':
      return new Set(mockReminders.map(r => r.id));
    case 'breeding':
      return new Set(mockBreeding.map(b => b.id));
    default:
      return new Set();
  }
};

/** Returns the Set of demo farm IDs so stores can also remove records tied to demo farms. */
export const getDemoFarmIds = (): Set<string> => new Set(mockFarms.map(f => f.id));

export const getMockData = (type: 'farms' | 'animals' | 'transactions' | 'healthRecords' | 'inventory' | 'reminders' | 'breeding' | 'users') => {
  switch (type) {
    case 'farms':
      return mockFarms;
    case 'animals':
      return mockAnimals;
    case 'transactions':
      return mockTransactions;
    case 'healthRecords':
      return mockHealthRecords;
    case 'inventory':
      return mockInventory;
    case 'reminders':
      return mockReminders;
    case 'breeding':
      return mockBreeding;
    case 'users':
      return mockUsers;
    default:
      return [];
  }
};

/**
 * Clear all app data from AsyncStorage.
 * This removes Zustand persisted stores and resets the app state.
 */
export const clearAllData = async () => {
  try {
    await AsyncStorage.multiRemove([
      // Demo mode runtime flag
      'demoDataEnabled',
      // Zustand persisted stores
      'farm-storage',
      'animal-storage',
      'financial-storage',
      'transaction-storage',
      'health-storage',
      'inventory-storage',
      'reminder-storage',
      'breeding-storage',
      'theme-storage',
      'auth-storage',
      // Legacy keys (for backwards compatibility)
      'farms',
      'animals',
      'transactions',
      'healthRecords',
      'users',
      'currentUser'
    ]);
    console.log('All data cleared successfully!');
    return true;
  } catch (error) {
    console.error('Failed to clear data:', error);
    return false;
  }
};
